//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolControlPanel
{
    using System;
    using System.Collections.Generic;
    
    public partial class classroom
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public classroom()
        {
            this.student_group = new HashSet<student_group>();
        }
    
        public int id { get; set; }
        public int primary_num { get; set; }
        public string secondary_num { get; set; }
        public int floor { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<student_group> student_group { get; set; }
        public override string ToString()
        {
            string str = "";
            if (string.IsNullOrWhiteSpace(secondary_num))
            {
                str = String.Format("{0}", primary_num);
            }
            else
            {
                str = String.Format("{0}-{1}", primary_num, secondary_num);
            }

            if (student_group.Count > 0)
            {
                str += " (Occupied by";
            }

            foreach (student_group s in student_group)
            {
                if (s.id != -1)
                {
                    str += " " + s.name;
                }
            }

            if (student_group.Count > 0)
            {
                str += ")";
            }

            return str;
        }
    }
}
