//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolControlPanel
{
    using System;
    using System.Collections.Generic;
    
    public partial class student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public student()
        {
            this.lesson_mark = new HashSet<lesson_mark>();
        }
    
        public int id { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string third_name { get; set; }
        public int student_group_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<lesson_mark> lesson_mark { get; set; }
        public virtual student_group student_group { get; set; }
        public override string ToString()
        {
            if (student_group_id == -1)
            {
                return String.Format("{0} {1} {2}", first_name, last_name, third_name);
            } 
            return String.Format("{0} {1} {2} (In {3})", first_name, last_name, third_name, student_group.name);
        }
    }
}
