//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolControlPanel
{
    using System;
    using System.Collections.Generic;
    
    public partial class student_group
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public student_group()
        {
            this.students = new HashSet<student>();
        }
    
        public int id { get; set; }
        public int teacher_id { get; set; }
        public int classroom_id { get; set; }
        public string name { get; set; }
        public int entry_year { get; set; }
        public int learning_program_id { get; set; }
    
        public virtual classroom classroom { get; set; }
        public virtual learning_program learning_program { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<student> students { get; set; }
        public virtual teacher teacher { get; set; }
    }
}
